export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const GET_CURRENT_USER_DATA_REQUEST = 'GET_CURRENT_USER_DATA_REQUEST';
export const GET_CURRENT_USER_DATA_SUCCESS = 'GET_CURRENT_USER_DATA_SUCCESS';
export const GET_CURRENT_USER_DATA_FAILURE = 'GET_CURRENT_USER_DATA_FAILURE';

export const SET_AUTH_STATE = 'SET_AUTH_STATE';

export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST';
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS';
export const CREATE_NEW_USER_FAILURE = 'CREATE_NEW_USER_FAILURE';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';

export const ERROR_CODE_ACCOUNT_EXISTS =
  'auth/account-exists-with-different-credential';

export const ERROR_MSG_ACCOUNT_EXISTS = `
  An account with an E-Mail address to
  this social account already exists. Try to login from
  this account instead and associate your social accounts on
  your personal account page.
`;
export const ERROR_CODE_ACCOUNT_ALREADY_EXISTS = 'auth/email-already-in-use';
export const ERROR_MSG_ACCOUNT_ALREADY_EXISTS = `
An account with an E-Mail address is already exists. Try to login from
  this account instead.`;
export const ERROR_CODE_WRONG_PASSWORD = 'auth/wrong-password';
export const ERROR_CODE_INVALID_LOGIN_CREDENTIALS = 'auth/invalid-login-credentials';
export const ERROR_MSG_WRONG_PASSWORD = `Wrong Password! \n Please try again`;
export const ERROR_CODE_TOO_MANY_ATTEMPTS = "auth/too-many-requests";
export const ERROR_MSG_TOO_MANY_ATTEMPTS = `Access to this account has been temporarily disabled due to many failed login attempts.\n You can immediately restore it by resetting your password or you can try again later.`
export const ERROR_CODE_INVALID_LOGIN_CREDS = "auth/invalid-login-credentials";
export const ERROR_MSG_INVALID_LOGIN_CREDS = `Email or Password wrong.! \n Please try again`
export const ERROR_CODE_MISSING_LOGIN_CREDS = "auth/missing-password";
export const ERROR_MSG_MISSING_LOGIN_CREDS = `Password Missing.! \n Please try again`
export const ERROR_CODE_USER_DELETED = 'auth/user-not-found';
export const ERROR_MSG_USER_DELETED = `User not found! \n Please try again`;
export const ERROR_CODE_INVALID_CREDENTIALS = 'auth/invalid-credential';
export const ERROR_MSG_INVALID_CREDENTIALS = `Invalid Credentials! \n Please try again`;
export const ERROR_CODE_INVALID_EMAIL = 'auth/invalid-email';
export const ERROR_MSG_INVALID_EMAIL = `Invalid Email! \n Please try again`;
export const ERROR_CODE_INVALID_PASSWORD = 'auth/invalid-password';
export const ERROR_MSG_INVALID_PASSWORD = `Invalid Password! \n Please try again`;
export const ERROR_CODE_INVALID_PHONE_NUMBER = 'auth/invalid-phone-number';
export const ERROR_MSG_INVALID_PHONE_NUMBER = `Invalid Phone Number! \n Please try again`;
export const ERROR_CODE_INVALID_USERNAME = 'auth/invalid-username';
export const ERROR_MSG_INVALID_USERNAME = `Invalid Username! \n Please try again`;

// Dashboard Types
export const FETCH_DASHBOARD_DATA_REQUEST = 'FETCH_DASHBOARD_DATA_REQUEST';
export const FETCH_DASHBOARD_DATA_SUCCESS = 'FETCH_DASHBOARD_DATA_SUCCESS';
export const FETCH_DASHBOARD_DATA_FAILURE = 'FETCH_DASHBOARD_DATA_FAILURE';

// Transactions Types
export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILURE = 'FETCH_TRANSACTIONS_FAILURE';

export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE';

export const UPDATE_TRANSACTION_REQUEST = 'UPDATE_TRANSACTION_REQUEST';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAILURE = 'UPDATE_TRANSACTION_FAILURE';

export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE';

// Loans Types
export const FETCH_LOANS_REQUEST = 'FETCH_LOANS_REQUEST';
export const FETCH_LOANS_SUCCESS = 'FETCH_LOANS_SUCCESS';
export const FETCH_LOANS_FAILURE = 'FETCH_LOANS_FAILURE';

export const CREATE_LOAN_REQUEST = 'CREATE_LOAN_REQUEST';
export const CREATE_LOAN_SUCCESS = 'CREATE_LOAN_SUCCESS';
export const CREATE_LOAN_FAILURE = 'CREATE_LOAN_FAILURE';

export const UPDATE_LOAN_REQUEST = 'UPDATE_LOAN_REQUEST';
export const UPDATE_LOAN_SUCCESS = 'UPDATE_LOAN_SUCCESS';
export const UPDATE_LOAN_FAILURE = 'UPDATE_LOAN_FAILURE';

export const DELETE_LOAN_REQUEST = 'DELETE_LOAN_REQUEST';
export const DELETE_LOAN_SUCCESS = 'DELETE_LOAN_SUCCESS';
export const DELETE_LOAN_FAILURE = 'DELETE_LOAN_FAILURE';

// Invoices Types
export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';

export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAILURE = 'CREATE_INVOICE_FAILURE';

export const UPDATE_INVOICE_REQUEST = 'UPDATE_INVOICE_REQUEST';
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';
export const UPDATE_INVOICE_FAILURE = 'UPDATE_INVOICE_FAILURE';

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAILURE = 'DELETE_INVOICE_FAILURE';

// Clients Types
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';

export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';
export const CREATE_CLIENT_FAILURE = 'CREATE_CLIENT_FAILURE';

export const UPDATE_CLIENT_REQUEST = 'UPDATE_CLIENT_REQUEST';
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS';
export const UPDATE_CLIENT_FAILURE = 'UPDATE_CLIENT_FAILURE';

export const DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST';
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS';
export const DELETE_CLIENT_FAILURE = 'DELETE_CLIENT_FAILURE';

// Analytics Types
export const FETCH_ANALYTICS_REQUEST = 'FETCH_ANALYTICS_REQUEST';
export const FETCH_ANALYTICS_SUCCESS = 'FETCH_ANALYTICS_SUCCESS';
export const FETCH_ANALYTICS_FAILURE = 'FETCH_ANALYTICS_FAILURE';

export const FETCH_KPI_DATA_REQUEST = 'FETCH_KPI_DATA_REQUEST';
export const FETCH_KPI_DATA_SUCCESS = 'FETCH_KPI_DATA_SUCCESS';
export const FETCH_KPI_DATA_FAILURE = 'FETCH_KPI_DATA_FAILURE';

export const FETCH_CHARTS_DATA_REQUEST = 'FETCH_CHARTS_DATA_REQUEST';
export const FETCH_CHARTS_DATA_SUCCESS = 'FETCH_CHARTS_DATA_SUCCESS';
export const FETCH_CHARTS_DATA_FAILURE = 'FETCH_CHARTS_DATA_FAILURE';

// Business Profile Types
export const FETCH_BUSINESS_PROFILE_REQUEST = 'FETCH_BUSINESS_PROFILE_REQUEST';
export const FETCH_BUSINESS_PROFILE_SUCCESS = 'FETCH_BUSINESS_PROFILE_SUCCESS';
export const FETCH_BUSINESS_PROFILE_FAILURE = 'FETCH_BUSINESS_PROFILE_FAILURE';

export const UPDATE_BUSINESS_PROFILE_REQUEST = 'UPDATE_BUSINESS_PROFILE_REQUEST';
export const UPDATE_BUSINESS_PROFILE_SUCCESS = 'UPDATE_BUSINESS_PROFILE_SUCCESS';
export const UPDATE_BUSINESS_PROFILE_FAILURE = 'UPDATE_BUSINESS_PROFILE_FAILURE';

// Account Settings Types
export const FETCH_ACCOUNT_SETTINGS_REQUEST = 'FETCH_ACCOUNT_SETTINGS_REQUEST';
export const FETCH_ACCOUNT_SETTINGS_SUCCESS = 'FETCH_ACCOUNT_SETTINGS_SUCCESS';
export const FETCH_ACCOUNT_SETTINGS_FAILURE = 'FETCH_ACCOUNT_SETTINGS_FAILURE';

export const UPDATE_ACCOUNT_SETTINGS_REQUEST = 'UPDATE_ACCOUNT_SETTINGS_REQUEST';
export const UPDATE_ACCOUNT_SETTINGS_SUCCESS = 'UPDATE_ACCOUNT_SETTINGS_SUCCESS';
export const UPDATE_ACCOUNT_SETTINGS_FAILURE = 'UPDATE_ACCOUNT_SETTINGS_FAILURE';

// System Preferences Types
export const FETCH_SYSTEM_PREFERENCES_REQUEST = 'FETCH_SYSTEM_PREFERENCES_REQUEST';
export const FETCH_SYSTEM_PREFERENCES_SUCCESS = 'FETCH_SYSTEM_PREFERENCES_SUCCESS';
export const FETCH_SYSTEM_PREFERENCES_FAILURE = 'FETCH_SYSTEM_PREFERENCES_FAILURE';

export const UPDATE_SYSTEM_PREFERENCES_REQUEST = 'UPDATE_SYSTEM_PREFERENCES_REQUEST';
export const UPDATE_SYSTEM_PREFERENCES_SUCCESS = 'UPDATE_SYSTEM_PREFERENCES_SUCCESS';
export const UPDATE_SYSTEM_PREFERENCES_FAILURE = 'UPDATE_SYSTEM_PREFERENCES_FAILURE';

// Support Types
export const FETCH_SUPPORT_TICKETS_REQUEST = 'FETCH_SUPPORT_TICKETS_REQUEST';
export const FETCH_SUPPORT_TICKETS_SUCCESS = 'FETCH_SUPPORT_TICKETS_SUCCESS';
export const FETCH_SUPPORT_TICKETS_FAILURE = 'FETCH_SUPPORT_TICKETS_FAILURE';

export const CREATE_SUPPORT_TICKET_REQUEST = 'CREATE_SUPPORT_TICKET_REQUEST';
export const CREATE_SUPPORT_TICKET_SUCCESS = 'CREATE_SUPPORT_TICKET_SUCCESS';
export const CREATE_SUPPORT_TICKET_FAILURE = 'CREATE_SUPPORT_TICKET_FAILURE';

export const UPDATE_SUPPORT_TICKET_REQUEST = 'UPDATE_SUPPORT_TICKET_REQUEST';
export const UPDATE_SUPPORT_TICKET_SUCCESS = 'UPDATE_SUPPORT_TICKET_SUCCESS';
export const UPDATE_SUPPORT_TICKET_FAILURE = 'UPDATE_SUPPORT_TICKET_FAILURE';

// Security/Session Types
export const FETCH_SESSIONS_REQUEST = 'FETCH_SESSIONS_REQUEST';
export const FETCH_SESSIONS_SUCCESS = 'FETCH_SESSIONS_SUCCESS';
export const FETCH_SESSIONS_FAILURE = 'FETCH_SESSIONS_FAILURE';

export const REVOKE_SESSION_REQUEST = 'REVOKE_SESSION_REQUEST';
export const REVOKE_SESSION_SUCCESS = 'REVOKE_SESSION_SUCCESS';
export const REVOKE_SESSION_FAILURE = 'REVOKE_SESSION_FAILURE';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';

export const FETCH_2FA_STATUS_REQUEST = 'FETCH_2FA_STATUS_REQUEST';
export const FETCH_2FA_STATUS_SUCCESS = 'FETCH_2FA_STATUS_SUCCESS';
export const FETCH_2FA_STATUS_FAILURE = 'FETCH_2FA_STATUS_FAILURE';

// Subscription Types
export const SUBSCRIBE_PLAN_REQUEST = 'SUBSCRIBE_PLAN_REQUEST';
export const SUBSCRIBE_PLAN_SUCCESS = 'SUBSCRIBE_PLAN_SUCCESS';
export const SUBSCRIBE_PLAN_FAILURE = 'SUBSCRIBE_PLAN_FAILURE';